### ISSUE TITLE
程序报错，但仍在运行

### ISSUE THREAD

**Issue by d233hj** [shaww855/acfun-live#38]
在输入所有参数后，

程序报错如下：

![图片](https://user-images.githubusercontent.com/78169764/161976065-36f860e7-7738-4588-baa4-4dbeb59141d6.png)
![图片](https://user-images.githubusercontent.com/78169764/161976145-99f2956b-944d-4982-93a2-d27861a53c9e.png)
![图片](https://user-images.githubusercontent.com/78169764/161976207-2c9d1396-5fcd-41f6-bbfd-a77f85b67f61.png)
![图片](https://user-images.githubusercontent.com/78169764/161976227-d2b73678-d8b4-4447-8aa6-34f234714244.png)
![图片](https://user-images.githubusercontent.com/78169764/161976264-0f935901-3df8-4b8b-acfb-c3aa1dd1b9ce.png)
![图片](https://user-images.githubusercontent.com/78169764/161976294-f2c87d2b-0762-4b6f-8c8f-528999a29a41.png)
![图片](https://user-images.githubusercontent.com/78169764/161976320-0b226e41-f0a4-4576-bf20-42713f24e002.png)
![图片](https://user-images.githubusercontent.com/78169764/161976362-af832e63-6783-4dc1-8414-1602fc41f0d0.png)
![图片](https://user-images.githubusercontent.com/78169764/161976392-78e35ab0-6026-4fec-b04a-3673fd885e4f.png)
![图片](https://user-images.githubusercontent.com/78169764/161976426-d752aa74-4d75-4c27-b33e-736f5f7cdbe9.png)
![图片](https://user-images.githubusercontent.com/78169764/161976449-4c163c63-9d20-4f46-a799-31da4bb57fac.png)
![图片](https://user-images.githubusercontent.com/78169764/161976466-301daa33-d657-46d7-b850-9cdc193dd4aa.png)
![图片](https://user-images.githubusercontent.com/78169764/161976507-36d90ecf-68f3-4239-aa85-c83e8dd91eb9.png)

开启调试并重新启动工具以后，仍报同样错误。此时前台打开了所有挂牌子直播间，并同时播放。在前台打开的直播间中，正确打开的直播间均在播放视频和声音。
但有部分直播间无法显示画面和声音，怀疑是带宽不足，不能同时打开过多直播间。
我的带宽为10~20M之间。

**Comment by shaww855** [comment]
抱歉，今天才看到
建议用官方弹幕工具挂牌子，也就是 config.json 文件里的 `useObsDanmaku` 设为 `true`
有部分报错是主站的错误，被我捕获到了，不影响挂牌子，考虑下次迭代隐藏此类无用信息
