### ISSUE TITLE
我经常出现无法登陆的情况

### ISSUE THREAD

**Issue by MsLingYue** [shaww855/acfun-live#51]
从很久以前用这个工具开始就经常会出现这种情况，每个版本都有时候出现登陆超时，几天能用几天又用不了的，每次都是自己好了，一直找不到原因，扫码登陆的话一直加载不出二维码，大佬能看看吗，打开调试模式的话弹出的是A站访问异常的页面

![屏幕截图(1884)](https://user-images.githubusercontent.com/45250200/182585437-1354c837-65bc-4bd9-aa57-9d09fbec2463.png)

![d](https://user-images.githubusercontent.com/45250200/182586935-515d0559-5879-436f-b6c7-ceac5f75bb64.jpg)

**Comment by shaww855** [comment]
是最新版吗，会不会是访问太频繁了
另外二维码是完全出不来么，如果命令提示符里乱码，会有额外一个二维码图片生成在程序目录的

**Comment by MsLingYue** [comment]
是最新版的，之前的版本也是有这种情况，二维码加载不了，文件夹里图片也没有生成

**Comment by shaww855** [comment]
没有遇到过欸，会不会是网络环境原因，直接用浏览器开A站扫码正常吗

**Comment by MsLingYue** [comment]
我也不知道，换浏览器也不行，都一样，但是自己在网页登录都没问题呢

**Comment by MsLingYue** [comment]
> 没有遇到过欸，会不会是网络环境原因，直接用浏览器开A站扫码正常吗

好怪，但是找到解决办法了，在打开工具之前先挂个国外的梯子，然后工具开始扫描到直播间了就可以关掉梯子正常运行了

**Comment by shaww855** [comment]
应该就是网络问题了，没有其他用户反馈这种情况
建议在关闭梯子后过一段时间再看看有没有正常运行
