### ISSUE TITLE
windows上指定chrome启动时白屏

### ISSUE THREAD

**Issue by shaww855** [shaww855/acfun-live#62]
正在研究解决方法，Edge暂时不受影响（验证了下，部分win10也会白屏）

**Comment by shaww855** [comment]
已破案，官方的bug
puppeteer/puppeteer/issues#13012

准备降级

**Comment by shaww855** [comment]
降级没用，基本确定是Chromium的问题
[Windows are showing up in headless mode on Windows](https://issues.chromium.org/issues/362706121)

会影响到所有使用Chromium内核的浏览器，包括但不限于Edge、Chrome、360浏览器。。。
等官方修复罢

**Comment by Aramil1** [comment]
哦 原来是这样
